<?php

/**
 * BaseInterest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $question_id
 * @property integer $user_id
 * @property timestamp $created_at
 * @property Question $Question
 * @property sfGuardUser $User
 * 
 * @method integer     getQuestionId()  Returns the current record's "question_id" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method timestamp   getCreatedAt()   Returns the current record's "created_at" value
 * @method Question    getQuestion()    Returns the current record's "Question" value
 * @method sfGuardUser getUser()        Returns the current record's "User" value
 * @method Interest    setQuestionId()  Sets the current record's "question_id" value
 * @method Interest    setUserId()      Sets the current record's "user_id" value
 * @method Interest    setCreatedAt()   Sets the current record's "created_at" value
 * @method Interest    setQuestion()    Sets the current record's "Question" value
 * @method Interest    setUser()        Sets the current record's "User" value
 * 
 * @package    quark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInterest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('interest');
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Question', array(
             'local' => 'question_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}