<?php

/**
 * BaseAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $question_id
 * @property integer $user_id
 * @property string $body
 * @property timestamp $created_at
 * @property integer $votes
 * @property boolean $accepted
 * @property Question $Question
 * @property sfGuardUser $User
 * @property Doctrine_Collection $Rating
 * @property Doctrine_Collection $Accept
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getQuestionId()  Returns the current record's "question_id" value
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method string              getBody()        Returns the current record's "body" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method integer             getVotes()       Returns the current record's "votes" value
 * @method boolean             getAccepted()    Returns the current record's "accepted" value
 * @method Question            getQuestion()    Returns the current record's "Question" value
 * @method sfGuardUser         getUser()        Returns the current record's "User" value
 * @method Doctrine_Collection getRating()      Returns the current record's "Rating" collection
 * @method Doctrine_Collection getAccept()      Returns the current record's "Accept" collection
 * @method Answer              setId()          Sets the current record's "id" value
 * @method Answer              setQuestionId()  Sets the current record's "question_id" value
 * @method Answer              setUserId()      Sets the current record's "user_id" value
 * @method Answer              setBody()        Sets the current record's "body" value
 * @method Answer              setCreatedAt()   Sets the current record's "created_at" value
 * @method Answer              setVotes()       Sets the current record's "votes" value
 * @method Answer              setAccepted()    Sets the current record's "accepted" value
 * @method Answer              setQuestion()    Sets the current record's "Question" value
 * @method Answer              setUser()        Sets the current record's "User" value
 * @method Answer              setRating()      Sets the current record's "Rating" collection
 * @method Answer              setAccept()      Sets the current record's "Accept" collection
 * 
 * @package    quark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnswer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('answer');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('body', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('votes', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('accepted', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Question', array(
             'local' => 'question_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Rating', array(
             'local' => 'id',
             'foreign' => 'answer_id'));

        $this->hasMany('Accept', array(
             'local' => 'id',
             'foreign' => 'answer_id'));
    }
}