<?php

/**
 * BaseStaticContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $title
 * @property string $body
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property sfGuardUser $User
 * 
 * @method integer       getId()         Returns the current record's "id" value
 * @method integer       getUserId()     Returns the current record's "user_id" value
 * @method string        getTitle()      Returns the current record's "title" value
 * @method string        getBody()       Returns the current record's "body" value
 * @method timestamp     getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp     getUpdatedAt()  Returns the current record's "updated_at" value
 * @method sfGuardUser   getUser()       Returns the current record's "User" value
 * @method StaticContent setId()         Sets the current record's "id" value
 * @method StaticContent setUserId()     Sets the current record's "user_id" value
 * @method StaticContent setTitle()      Sets the current record's "title" value
 * @method StaticContent setBody()       Sets the current record's "body" value
 * @method StaticContent setCreatedAt()  Sets the current record's "created_at" value
 * @method StaticContent setUpdatedAt()  Sets the current record's "updated_at" value
 * @method StaticContent setUser()       Sets the current record's "User" value
 * 
 * @package    quark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStaticContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('static_content');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}