<?php

/**
 * BaseRating
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $answer_id
 * @property integer $user_id
 * @property integer $value
 * @property Answer $Answer
 * @property sfGuardUser $User
 * 
 * @method integer     getAnswerId()  Returns the current record's "answer_id" value
 * @method integer     getUserId()    Returns the current record's "user_id" value
 * @method integer     getValue()     Returns the current record's "value" value
 * @method Answer      getAnswer()    Returns the current record's "Answer" value
 * @method sfGuardUser getUser()      Returns the current record's "User" value
 * @method Rating      setAnswerId()  Sets the current record's "answer_id" value
 * @method Rating      setUserId()    Sets the current record's "user_id" value
 * @method Rating      setValue()     Sets the current record's "value" value
 * @method Rating      setAnswer()    Sets the current record's "Answer" value
 * @method Rating      setUser()      Sets the current record's "User" value
 * 
 * @package    quark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRating extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rating');
        $this->hasColumn('answer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Answer', array(
             'local' => 'answer_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}