<?php

/**
 * BaseRelevancy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $answer_id
 * @property integer $user_id
 * @property integer $score
 * @property timestamp $created_at
 * @property Answer $Answer
 * @property User $User
 * 
 * @method integer   getAnswerId()   Returns the current record's "answer_id" value
 * @method integer   getUserId()     Returns the current record's "user_id" value
 * @method integer   getScore()      Returns the current record's "score" value
 * @method timestamp getCreatedAt()  Returns the current record's "created_at" value
 * @method Answer    getAnswer()     Returns the current record's "Answer" value
 * @method User      getUser()       Returns the current record's "User" value
 * @method Relevancy setAnswerId()   Sets the current record's "answer_id" value
 * @method Relevancy setUserId()     Sets the current record's "user_id" value
 * @method Relevancy setScore()      Sets the current record's "score" value
 * @method Relevancy setCreatedAt()  Sets the current record's "created_at" value
 * @method Relevancy setAnswer()     Sets the current record's "Answer" value
 * @method Relevancy setUser()       Sets the current record's "User" value
 * 
 * @package    quark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRelevancy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('relevancy');
        $this->hasColumn('answer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('score', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Answer', array(
             'local' => 'answer_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}