<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nickname
 * @property string $first_name
 * @property string $last_name
 * @property timestamp $created_at
 * @property Doctrine_Collection $ask_user
 * @property Doctrine_Collection $Interest
 * @property Doctrine_Collection $Relevancy
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getNickname()   Returns the current record's "nickname" value
 * @method string              getFirstName()  Returns the current record's "first_name" value
 * @method string              getLastName()   Returns the current record's "last_name" value
 * @method timestamp           getCreatedAt()  Returns the current record's "created_at" value
 * @method Doctrine_Collection getAskUser()    Returns the current record's "ask_user" collection
 * @method Doctrine_Collection getInterest()   Returns the current record's "Interest" collection
 * @method Doctrine_Collection getRelevancy()  Returns the current record's "Relevancy" collection
 * @method User                setId()         Sets the current record's "id" value
 * @method User                setNickname()   Sets the current record's "nickname" value
 * @method User                setFirstName()  Sets the current record's "first_name" value
 * @method User                setLastName()   Sets the current record's "last_name" value
 * @method User                setCreatedAt()  Sets the current record's "created_at" value
 * @method User                setAskUser()    Sets the current record's "ask_user" collection
 * @method User                setInterest()   Sets the current record's "Interest" collection
 * @method User                setRelevancy()  Sets the current record's "Relevancy" collection
 * 
 * @package    quark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('nickname', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('first_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('last_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Question as ask_user', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Interest', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Relevancy', array(
             'local' => 'id',
             'foreign' => 'user_id'));
    }
}