<?php

/**
 * AnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Answer');
    }

  /**
   * Execute an update for the interested users counter.
   *
   */
  public function updateAnswerRating($aid, $amount) {
    $q = Doctrine_Query::create()
      ->update('Answer a')
      ->set('a.votes','a.votes + ?', $amount)
      ->where('a.id = ?',$aid)
      ->execute();
  }

  /**
   * Get the last 10 answers for a given user id.
   */
  public function getLastFiftyByUserId($user_id)
  {
    $q = Doctrine_Query::create()
      ->select('q.title, a.votes')
      ->from('Answer a')
      ->innerJoin('a.Question q ON a.question_id = q.id')
      ->where('a.user_id = ?', $user_id)
      ->limit(50);
    return $q->execute();
  }
}