<?php

/**
 * QuestionTagTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuestionTagTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object QuestionTagTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('QuestionTag');
  }
  
  /**
   * Avoid duplicated into this table.
   */
  public static function avoidDuplicated($question, $tag)
  {
    $q = Doctrine_Query::create()
      ->from('QuestionTag qt')
      ->where('qt.question_id = ?', $question)
      ->andWhere('qt.tag_id = ?', $tag);
    $array = $q->fetchArray();
    if (!$array)
      return true;
    else
      return false;
  }
}