<?php

/**
 * Rating
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Rating extends BaseRating {


	public function save(Doctrine_Connection $conn = null) {
		$conn = Doctrine_Manager::getInstance()->getCurrentConnection();
		$conn->beginTransaction();
		try {
			$ret = parent::save($conn);
			$answer = $this->getAnswer();
			$votes = $answer->getVotes();
			$answer->setVotes($votes + 1);
			$answer->save($conn);
			$conn->commit();
			return $ret;
		} catch (Exception $e) {
			$conn->rollBack();
			throw $e;
		}
	}
}
