<?php

/**
 * RelevancyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RelevancyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RelevancyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Relevancy');
    }
}