<?php

/**
 * TagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tag');
    }

    public static function getRecentTags()
    {
      $q = Doctrine_Query::create()
        ->select('t.name, COUNT(q.tag_id)')
        ->from('Tag t')
        ->innerJoin('t.QuestionTag q')
        ->orderBy('t.name')
        ->groupBy('q.tag_id')
        ->limit(30);
      
      return $q->fetchArray();
    }
}