# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# rules
question:
  class:   sfDoctrineRouteCollection
  options: { model: Question }

answer:
  class:   sfDoctrineRouteCollection
  options: { model: Answer }

# Show the question page
question_show:
  url:	/question/:id/:title_slug
  class:   sfDoctrineRoute
  options: { model: Question, type: object }
  param: { module: question, action: show }
  requirements:
    id: \d+
    sf_method: [get]

# Increase the views counter for the question page.
increase_view_count:
  url: /post/:id/:token
  param: {module: question, action: increaseviewcount}
  class: sfRequestRoute
  requirements:
    id: \d+
    sf_method: [get]

# vote
vote:
  url: /vote/:id/:type/:token
  param: {module: question, action: vote}
  class: sfRequestRoute
  requirements:
    id: \d+
    type: (up|down)
    sf_method: [get]

# undo an existing vote
undo_vote:
  url: /vote/undo/:id/:type/:token
  param: {module: question, action: undovote}
  class: sfRequestRoute
  requirements:
    id: \d+
    type: (up|down)
    sf_method: [get]

# Show the homepage
homepage:
  url:   /
  param: { module: question, action: index }

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }
#
#default:
#  url:   /:module/:action/*

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

