# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# rules
question:
  class:   sfDoctrineRouteCollection
  options: { model: Question }

answer:
  class:   sfDoctrineRouteCollection
  options: { model: Answer }

question_show:
  url:	/question/:id/:title_slug
  class:   sfDoctrineRoute
  options: { model: Question, type: object }
  param: { module: question, action: show }
  requirements:
    id: \d+
    sf_method: [get]

homepage:
  url:   /
  param: { module: question, action: index }

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }
#
#default:
#  url:   /:module/:action/*
