# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:

    # Enable i18n
    i18n: true

    # Form security secret (CSRF protection)
    csrf_secret:            bd1f6ab14a017ee6a1c09e068168caf55ae964d2

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    # Enable login module
    enabled_modules: [default, sfGuardAuth, sfGuardPermission, sfGuardUser, sfApply]

  .actions:
    login_module:    sfGuardAuth
    login_action:    signin

    secure_module:   sfGuardAuth
    secure_action:   secure

