generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Question
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          question
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Question Management
        display: [=title, created_at]
        sort: [created_at, title]
      filter:  ~
      form:    ~
      edit:
        title: Editing Question "%%title%%" (#%%id%%)
      new:
        title: New Question
