all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=quark_old;unix_socket=/var/run/mysqld/mysqld.sock'
      username: quark_old
      password: quark_old
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=quark_old;unix_socket=/var/run/mysqld/mysqld.sock'
      username: quark_old
      password: quark_old