Question:
  columns:
    id:								{type: integer, notnull: true, autoincrement: true, primary: true}
    user_id:					{type: integer, notnull: true}
    title:						{type: string(255), notnull: true}
    body:							{type: string(1000)}
    views:            {type: integer, notnull: true, default: 0}
    created_at:				{type: timestamp, notnull: true}
    updated_at:				{type: timestamp, notnull: true}
    interested_users:	{type: integer, default: 0}
  relations:
    User:							{onDelete: CASCADE, local: user_id, class: sfGuardUser}

Answer:
  columns:
    id:							{type: integer, notnull: true, autoincrement: true, primary: true}
    question_id:		{type: integer, notnull: true}
    user_id:				{type: integer, notnull: true}
    body:						{type: string(1000)}
    created_at:			{type: timestamp, notnull: true}
    votes:					{type: integer, default:0}
    accepted:       {type: boolean, default: false}
  relations:
    Question:				{onDelete: CASCADE, local: question_id, foreign: id, foreignAlias: ask_question}
    User:						{onDelete: CASCADE, local: user_id, class: sfGuardUser}

Interest:
  columns:
    question_id:		{type: integer, notnull: true}
    user_id:				{type: integer, notnull: true}
    value:          {type: integer, notnull: true, unsigned: false}
    created_at:			{type: timestamp, notnull: true}    
  relations:
    Question:				{onDelete: CASCADE, local: question_id, foreign: id}
    User:						{onDelete: CASCADE, local: user_id, class: sfGuardUser}

Rating:
  columns:
    answer_id:			{type: integer, notnull: true}
    user_id:				{type: integer, notnull: true}
    value:          {type: integer, notnull: true, unsigned: false}
    created_at:			{type: timestamp, notnull: true}
  relations:
    Answer:					{onDelete: CASCADE, local: answer_id, foreign: id}
    User:						{onDelete: CASCADE, local: user_id, class: sfGuardUser}

Accept:
  columns:
    question_id:    {type: integer, notnull: true}
    answer_id:      {type: integer, notnull: true}
    created_at:     {type: timestamp, notnull: true}
  relations:
    Question:				{onDelete: CASCADE, local: question_id, foreign: id}
    Answer:         {onDelete: CASCADE, local: answer_id, foreign: id}

StaticContent:
  columns:
    id:               {type: integer, notnull: true, autoincrement: true, primary: true}
    user_id:          {type: integer, notnull: true}
    title:            {type: string(255), notnull: true}
    path:             {type: varchar(50), notnull: true, unique: true}
    body:             {type: string(1000)}
    created_at:       {type: timestamp, notnull: true}
    updated_at:       {type: timestamp, notnull: true}
  relations:
    User:             {onDelete: CASCADE, local: user_id, class: sfGuardUser}